stages:
  - merge

new_version:
  stage: merge
  variables:
    GIT_STRATEGY: fetch    
    GIT_DEPTH: 0    
  script:
    - git checkout -b new-release
    - CURRENT_VERSION=$(cat version.txt)
    - NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2"."$3+1}')
    - echo $NEW_VERSION > version.txt
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_LOGIN}"
    - git add version.txt
    - git commit -m "New version $NEW_VERSION"
    - git push origin new-release

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'