stages:
  - merge
  - sync

squash_merge:
  stage: merge
  variables:
    TERRAFORM_MODULE_VERSION : ${CI_COMMIT_TAG}
  script:
    - git checkout release-branch
    - git merge --squash main
    - git commit -m "${TERRAFORM_MODULE_VERSION}"

sync_to_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.name "GitLab CI/CD"
    - git config --global user.email "your-email@example.com"
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/yourusername/your-repo.git
    - git checkout release-branch 
    - git push github main
  rules:
    - if: $CI_COMMIT_TAG
